#!/bin/bash
ROOTDIR="$(pwd)"
cd `dirname "$0"` && cd ..

TMPFILE=`mktemp`
./gradlew --console=plain :clikt:getShadowJar | tee $TMPFILE
JARFILE=`cat $TMPFILE | awk '/shadowJar:/  {print $2}'`
echo jarfile: $JARFILE
rm $TMPFILE
echo changing to dir $ROOTDIR
cd "$ROOTDIR"
exec java -jar $JARFILE "$@"


