#
#Gradle
org.gradle.jvmargs=-Xmx3072M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
#
project.group=io.github.danbrough.katty
project.version=0.0.1-alpha01
#includeKlogPath=../klog
#
#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
kotlin.native.ignoreDisabledTargets=true
#
#JetBrains
org.jetbrains.compose.experimental.jscanvas.enabled=true
#
#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
#

