#!/bin/bash
cd `dirname "$0"`

TMPFILE=`mktemp`
./gradlew --console=plain :demo:getShadowJar | tee $TMPFILE
JARFILE=`cat $TMPFILE | awk '/shadowJar:/  {print $2}'`
echo jarfile: $JARFILE
rm $TMPFILE
exec java -jar $JARFILE "$@"


