#!/bin/bash
DIR="$(pwd)"
cd `dirname "$0"`

TMPFILE=`mktemp`
./gradlew --console=plain :demo:getShadowJar | tee $TMPFILE
JARFILE=`cat $TMPFILE | awk '/shadowJar:/  {print $2}'`
echo jarfile: $JARFILE
rm $TMPFILE
echo changing to dir $DIR
cd "$DIR"
exec java -jar $JARFILE "$@"


