#!/bin/bash

cd "$(dirname "$0")" && source ./common.sh

TMPFILE=`mktemp`
./gradlew --console=plain :$MODULE:getShadowJar | tee $TMPFILE
JARFILE=`cat $TMPFILE | awk '/shadowJar:/  {print $2}'`
echo jarfile: $JARFILE
rm $TMPFILE
echo changing to dir $ROOTDIR
cd "$ROOTDIR"
exec java -jar $JARFILE "$@"


