#!/bin/bash

cd "$(dirname "$0")" && source ./common.sh


TMP_FILE=`mktemp`
set -o pipefail
( ./gradlew --console=plain :$MODULE:getShadowJar | tee $TMP_FILE ) || exit 1
JARFILE=`cat $TMP_FILE | awk '/shadowJar:/  {print $2}'`
echo jarfile: $JARFILE
rm $TMP_FILE
echo changing to dir $ROOTDIR
cd "$ROOT_DIR"
exec java -jar $JARFILE "$@"


