#!/bin/bash

cd "$(dirname "$0")" && source ./common.sh

./gradlew  :demo:jsDevelopmentExecutableCompileSync :demo:kotlinNodeJsSetup :kotlinYarnSetup :kotlinNpmInstall  || exit 1


NODE="$(find $GRADLE_USER_HOME/nodejs/  -type f -name node  -printf "%T@ %p\n" | sort -rn | head -n 1 | cut -d' ' -f2-)"

$NODE --require "$ROOT_DIR/build/js/node_modules/source-map-support/register.js" \
"$ROOT_DIR/build/js/node_modules/katty-demo/kotlin/katty-demo.js" "$@"





